dt_top = "Renamed Files"
dt_top_text = "ファイルを選択"
dt_root_ms = "名称変更するファイルを選択"
dt_root_text = "ファイル選択"
ms_newnames = "新しいファイル名(順番に注意)"
ms_noinput = "ファイル名未入力"
ms_dontmatch = "置換対象とファイル名数が一致しません"
ms_success = "完了"